import { Metadata } from 'next'
import '@/styles/reset.css'
import '@vook-client/design-system/style.css'

import ReactQueryProvider from '@/providers/ReactQueryProvider'
import { pretendard } from '@/styles/fonts'
import { Sidebar } from '@/components/Sidebar'

import { mainArea } from './layout.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="kr">
      <body className={pretendard.className}>
        <ReactQueryProvider>
          <Sidebar />
          <main className={mainArea}>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  )
}

export default RootLayout
